### ISSUE TITLE
Reformatting the MLOps section

### ISSUE THREAD

**Issue by stefanodallapalma** [visenger/awesome-mlops#42]
Hi,

In a previous PR, I suggested simplifying the section "MLOps," which IMHO looks a little confusing, given that it follows different citation styles.
In response to @visenger [question](https://github.com/visenger/awesome-mlops/pull/41#issuecomment-769107040) (*Would you take the lead and "chicago-fy" the paper's references?*), yes, I can do that.
However, on the one hand, I wonder whether adding authors and venue information is really needed, considering that a large part of the text is made of that information, and the remaining is the title, which is the most useful information.
On the other hand, most of the list items in the other sections have an elementary format given by their titles only. 

That being said, I would like to propose two alternatives to reformat the MLOps section:

## Alternative 1
Reformat each item using the title only, and link it to the raw document or its digital library page (if available). For example

**MLOps Papers**
1. [Challenges in deploying machine learning: a survey of case studies](https://arxiv.org/abs/2011.09926).
1. [Challenges in the deployment and operation of machine learning in practice](https://aisel.aisnet.org/ecis2019_rp/163/).
1. [On challenges in machine learning model management](https://web.kaust.edu.sa/Faculty/MarcoCanini/classes/CS290E/F19/papers/challenges.pdf).

## Alternative 2
Reformat each item using the title plus a brief description from its abstract, and link it through a "Go to paper" to the raw document or its digital library page (if available). As [here](https://github.com/stefanodallapalma/awesome-mlops/tree/mlops-papers-formatting#mlops-papers). For example:

**MLOps Papers**
1. **(2021) Challenges in deploying machine learning: a survey of case studies.** This survey reviews published reports of deploying machine learning solutions in a variety of use cases, industries and applications and extracts practical considerations corresponding to stages of the machine learning deployment workflow. [Go to paper](https://arxiv.org/abs/2011.09926).
1. **(2019) Challenges in the deployment and operation of machine learning in practice.** In this work, the authors target to systematically elicit the challenges in deployment and operation to enable broader practical dissemination of machine learning applications. [Go to paper](https://aisel.aisnet.org/ecis2019_rp/163/).
1. **(2018) On challenges in machine learning model management.** This paper discusses a selection of ML use cases, develops an overview over conceptual, engineering, and data-processing related challenges arising in the management of the
corresponding ML models, and points out future research directions. [Go to paper](https://web.kaust.edu.sa/Faculty/MarcoCanini/classes/CS290E/F19/papers/challenges.pdf).

Alternative 1 is consistent with the rest of the README; while alternative 2 provides more details about each paper without being too difficult too read. In summary, I believe it helps better identify the papers of interest.

While I agree to give credit to the authors of the papers, they are listed in the papers themselves and on the digital library page. Therefore, I found it either redundant and cumbersome. 

**Note:** I do not want to dictate new rules on how to format the document. I simply find that this way would be more effective to identify the resources of interest for a given search, at least for me :)

Of course, I will be in charge of those modifications.

What do you think?

**Comment by visenger** [comment]
These are valid points, @stefanodallapalma !
I really like the idea of the "Alternative 2"

Would you like to modify the whole section Papers, Stefano?

**Comment by stefanodallapalma** [comment]
Thank you. Yes, I'd like to modify the whole section Papers. However, it will take me a while. If you don't mind I start by PR the three that I put in this example.

**Comment by visenger** [comment]
Sure! Go ahead @stefanodallapalma 
Thank you for your contribution 🙏

**Comment by stefanodallapalma** [comment]
HI @visenger,
because the README.md is notably increasing, what about providing a description of each section in the READEME, and link them to the respective file.md? 

For an example, [see here](https://github.com/stefanodallapalma/awesome-mlops/blob/mlops-papers/README.md#mlops-papers)

**Comment by visenger** [comment]
Hey @stefanodallapalma 
Let us proceed as you suggested with the papers section for a beginning.
We can refactor the remaining sections later.
Thanks!!
