### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by Nikronic** [visenger/awesome-mlops#5]
Hi, in the `machine learning` section, there is a formatting issue:
![image](https://user-images.githubusercontent.com/32401852/88201439-b1c8b600-cc5c-11ea-9559-a69cbfd5c4fd.png)
Line 219-220, issue: a missed space

I would be happy If I could send a PR.

Thanks for great work.

**Comment by visenger** [comment]
Thanks for spotting this. 
Go ahead, PRs are welcome!
