### ISSUE TITLE
Engineering MLOps book

### ISSUE THREAD

**Issue by emmanuelraj7** [visenger/awesome-mlops#56]
Please add the book,

"Engineering MLOps: Rapidly build, test, and manage production-ready machine learning life cycles at scale" by Emmanuel Raj, 2021 - [https://www.packtpub.com/product/engineering-mlops/9781800562882](https://www.packtpub.com/product/engineering-mlops/9781800562882)

**Comment by visenger** [comment]
Hi, @emmanuelraj7 
please PR your book into the "Books" section.

**Comment by emmanuelraj7** [comment]
Hi @visenger PR made. Please add the book.
