### ISSUE TITLE
MLOps talk

### ISSUE THREAD

**Issue by emmanuelraj7** [visenger/awesome-mlops#57]
Please add this talk,

Emmanuel Raj - MLOps: Automated Machine Learning | PyData: [https://www.youtube.com/watch?v=m32k9jcY4pY](https://www.youtube.com/watch?v=m32k9jcY4pY)

**Comment by visenger** [comment]
@emmanuelraj7 you are welcome to PR your talk into the "Talks" section.

**Comment by emmanuelraj7** [comment]
Hi @visenger PR made. Please add the talk.
