### ISSUE TITLE
How are the diagrams created?

### ISSUE THREAD

**Issue by ravirajag** [visenger/awesome-mlops#71]
Hi @visenger 
Thank you for the amazing resources. Learnt a lot from them. May I know what tool you are using to create the diagrams

**Comment by visenger** [comment]
Thank you, @ravirajag for your kind feedback!
I am very happy to hear that this repository is helpful for you :)

All diagrams (also on ml-ops.org) are hand-made. I use iPad Pro, Pencil (Apple), and Paper app https://wetransfer.com/paper

**Comment by ravirajag** [comment]
Thank you for the quick response. Keep up the good work 👍👍
