### ISSUE TITLE
[Suggestion] Computer Vision Newsletter

### ISSUE THREAD

**Issue by dashagurova** [visenger/awesome-mlops#96]
I curate a bi-weekly community newsletter for computer vision practitioners. No marketing or product in it, just CV news, articles, learning resources, MLOps & DataOps, events, etc. It is free and focused on bringing value to the AI community. 
I would love to add it to the awesome-mlops repository.

[Here is the subscription link](https://info.superb-ai.com/ground-truth-newsletter-subscribe)
[Here is one of the last issues to check out](https://superb-ai-9384297.hs-sites.com/the-ground-truth-newsletter-issue-14).

**Comment by visenger** [comment]
Sure, @dashagurova , just PR your newsletter!

Thanks!
